import { PricingPlan } from '../types';

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'start',
    name: 'PLANO START',
    creationPrice: 300,
    monthlyPrice: 79.9,
    description: 'Ideal para autônomos e pequenos negócios que desejam iniciar a automação no WhatsApp com estabilidade.',
    accentColor: 'blue',
    targetAudience: 'Pequenos comércios, prestadores de serviços e autônomos',
    features: [
      { text: 'Suporte comercial', included: true },
      { text: 'Resposta rápida', included: true },
      { text: 'Setup básico configurado', included: true },
      { text: 'Monitoramento de servidor', included: true },
      { text: 'Infraestrutura estável', included: true },
      { text: 'Menu interativo & FAQ ágil', included: true },
      { text: 'Backup semanal em nuvem', included: true },
      { text: 'Integração avançada com IA Generativa', included: false },
      { text: 'Suporte 24 horas por dia', included: false },
    ],
  },
  {
    id: 'pro',
    name: 'PLANO PRO',
    badge: 'RECOMENDADO',
    isPopular: true,
    creationPrice: 599,
    monthlyPrice: 150.0,
    description: 'A escolha mais popular para empresas em expansão que exigem resposta acelerada e backup diário.',
    accentColor: 'cyan',
    targetAudience: 'Empresas em crescimento, clínicas, e-commerces e imobiliárias',
    features: [
      { text: 'Suporte prioritário', included: true, highlight: true },
      { text: 'Resposta acelerada', included: true, highlight: true },
      { text: 'Backup diário automático', included: true, highlight: true },
      { text: 'Monitoramento ativo 24/7', included: true },
      { text: 'Alta estabilidade de conexão', included: true },
      { text: 'Fluxos avançados de vendas & qualificação', included: true },
      { text: 'Transbordo inteligente para equipe humana', included: true },
      { text: 'Relatórios de métricas de conversão', included: true },
      { text: 'Suporte VIP exclusivo com gerente', included: false },
    ],
  },
  {
    id: 'premium',
    name: 'PLANO PREMIUM',
    creationPrice: 1670,
    monthlyPrice: 400.0,
    description: 'Potência máxima com Inteligência Artificial avançada, suporte contínuo 24/7 e atendimento VIP.',
    accentColor: 'purple',
    targetAudience: 'Grandes operações, redes de franquias, agências e alto volume',
    features: [
      { text: 'Integração total com IA (LLM/ChatGPT)', included: true, highlight: true },
      { text: 'Suporte técnico & operacional 24/7', included: true, highlight: true },
      { text: 'Atendimento VIP dedicado', included: true, highlight: true },
      { text: 'Monitoramento contínuo em tempo real', included: true },
      { text: 'Alta performance para altíssimo tráfego', included: true },
      { text: 'Treinamento de IA com dados da sua empresa', included: true },
      { text: 'Múltiplos números e atendentes sincronizados', included: true },
      { text: 'Integração com CRMs e Webhooks personalizados', included: true },
      { text: 'SLA garantido de 99.9% de uptime', included: true },
    ],
  },
];

export const COMPANY_CONTACTS = {
  name: 'PrimeConnect IA',
  slogan: 'Conecte. Automatize. Simplifique.',
  badge: 'Vendas & Automação',
  phoneDisplay: '(38) 9 9942-2060',
  phoneRaw: '5538999422060',
  email: 'primeconnectia2026@yahoo.com',
  instagram: '@prime.connectia',
  instagramUrl: 'https://instagram.com/prime.connectia',
  whatsappDirectUrl: 'https://wa.me/5538999422060?text=Ol%C3%A1!%20Vim%20pelo%20site%20da%20PrimeConnect%20IA%20e%20gostaria%20de%20saber%20mais%20sobre%20as%20solu%C3%A7%C3%B5es%20de%20chatbot.',
};
