import { Testimonial } from '../types';

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Dra. Mariana Vasconcelos',
    role: 'Diretora Médica',
    company: 'Clínica OdontoPrime & Estética',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=240&q=80',
    rating: 5,
    comment: 'Antes da PrimeConnect IA, perdíamos dezenas de pacientes que mandavam mensagem à noite ou no final de semana. Hoje, o chatbot responde em 3 segundos, tira dúvidas de procedimentos e já agenda a consulta na nossa agenda. Nosso faturamento aumentou 42% no primeiro mês!',
    metric: '+140% em agendamentos noturnos',
    segment: 'Saúde & Clínicas',
    verified: true,
  },
  {
    id: '2',
    name: 'Carlos Eduardo Barreto',
    role: 'CEO & Co-fundador',
    company: 'NextStore Eletrônicos',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=240&q=80',
    rating: 5,
    comment: 'Implementamos o Plano Pro com o servidor sob medida. A estabilidade é impressionante. Durante a Black Friday, o bot processou mais de 8 mil conversas simultâneas sem nenhuma lentidão, tirando dúvidas de estoque e enviando links de pagamento Pix no automático.',
    metric: 'R$ 68.000 recuperados em carrinhos',
    segment: 'E-commerce & Varejo',
    verified: true,
  },
  {
    id: '3',
    name: 'Renata Albuquerque',
    role: 'Gestora Comercial',
    company: 'Albuquerque Negócios Imobiliários',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=240&q=80',
    rating: 5,
    comment: 'O melhor é a triagem com IA. O robô pergunta a faixa de valor, o bairro e o tipo de imóvel que o cliente busca. Quando o corretor assume a conversa, o cliente já está 100% qualificado. Economizamos mais de 3 horas por dia de cada corretor.',
    metric: 'Tempo de resposta: < 2 seg',
    segment: 'Imobiliário & Construção',
    verified: true,
  },
  {
    id: '4',
    name: 'Felipe Martins',
    role: 'Diretor de Operações',
    company: 'SmartDelivery Logística',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=240&q=80',
    rating: 5,
    comment: 'O suporte comercial e a rapidez no setup foram diferenciais. Estávamos sofrendo com bloqueios em ferramentas baratas da concorrência. Na PrimeConnect IA, com o servidor dedicado e monitoramento ativo, temos 100% de estabilidade e paz de espírito.',
    metric: '99.9% Uptime garantido',
    segment: 'Logística & Serviços',
    verified: true,
  },
  {
    id: '5',
    name: 'Juliana Castro',
    role: 'Fundadora',
    company: 'Studio Bellas & Cursos',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=240&q=80',
    rating: 5,
    comment: 'Eu não conseguia atender o WhatsApp e atender as alunas ao mesmo tempo. A PrimeConnect IA foi a virada de chave do meu estúdio. O chatbot envia catálogo, tira dúvidas sobre datas dos cursos e recebe comprovantes. Nota 10!',
    metric: '+350 novos alunos inscritos',
    segment: 'Educação & Beleza',
    verified: true,
  },
];
